name: snapd
version: 0.8.0
repository: https://github.com/open-runtime/snapd.dart
description:
  Provides a client to access snapd, which allows you to manage, search and install snaps on a Linux system.

# publishable packages can't have git dependencies
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.8.0
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  test: ^1.16.8
  test_cov: ^1.0.1
  ubuntu_lints: ^0.4.0
